title:             The African-Arab Slave Trade
email:
description:       Mapping the East African Slave Trade to the Arabian Peninsula
author:            Gokh Amin Alshaif & Eric Massie
baseurl:           "/African-Arab-SlaveTrade" # Leave this alone if this is your main site (i.e. username.github.io). If instead this is a site for a project, e.g. username.github.io/
url:               "https://arabslavetrade.gokhamin.com" # or http://username.github.io/mycleverproject if it is a project site, or http://mylovelydomainname.com if you have a domain, and so on.

collections:
  pages:
    output: true
    permalink: /:name
  updates:
    output: true
    permalink: /updates/:name

# Social Profiles
twitter_username:
github_username:   galshaif
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
